---

ADMIN_PASSWORD: "{{ VAULT_ADMIN_PASSWORD }}"
AWS_ACCESSKEY: "{{ VAULT_AWS_ACCESSKEY }}"
AWS_SECRETKEY: "{{ VAULT_AWS_SECRETKEY }}"
ADMIN_HTTPS_PORT: "8443"
ADMIN_USER: "admin"
APP_TAG_KEY: "Application"
APP_TAG_VALUE: "${aws_tag_value}"